experiment_name: "fullLightV2"

# Dataset
image_size: 96
in_channels: 2

# ViT / DINO settings
patch_size: 8
out_dim: 768

# Training
batch_size: 64
epochs: 5
learning_rate: 1e-4
weight_decay: 0.05
num_workers: 4

# DINO Multi-crop
global_crops_scale: [0.5, 0.9]
local_crops_scale: [0.1, 0.4]
local_crops_number: 6

# Augmentation settings
augment:
  elastic_p: 0.4
  elastic_alpha_range: [4.0, 8.0] 
  elastic_sigma_range: [30.0, 40.0] 

  solarization_p: 0.05

  brightness_dapi_p: 0.05
  brightness_dapi_range: [0.5, 3.0]

  brightness_egfp_p: 0.05
  brightness_egfp_range: [0.5, 2.0]

  contrast_p: 0.2
  contrast_range: [0.9, 1.1]

  rotation_degrees: [-180, 180]      

  blur_global_p: 0.25
  blur_global_sigma: [1.0, 5.0]

  blur_local_p: 0.25
  blur_local_sigma: [0.1, 0.5]

  noise_global_p: 0.25
  noise_global_std: [0.001, 0.003]

  noise_local_p: 0.25
  noise_local_std: [0.001, 0.003]

# EMA
base_momentum: 0.996
max_momentum: 1.0

